const CREATE_CONTACT = "CREATE_CONTACT";
const CREATE_NEW_LIST = "CREATE_NEW_LIST";
const DELETE_CONTACT_INFO = "DELETE_CONTACT_INFO";
const DELETE_FROM_LIST = "DELETE_FROM_LIST";
const LOG_OUT = "LOG_OUT";
const MARK_AS_COMPLETE = "MARK_AS_COMPLETE";
const SHOW_ACTIVE = "SHOW_ACTIVE";
const SHOW_ALL = "SHOW_ALL";
const SHOW_COMPLETED = "SHOW_COMPLETED";

module.exports = {
  CREATE_CONTACT,
  CREATE_NEW_LIST,
  DELETE_CONTACT_INFO,
  DELETE_FROM_LIST,
  LOG_OUT,
  MARK_AS_COMPLETE,
  SHOW_ACTIVE,
  SHOW_ALL,
  SHOW_COMPLETED
};
